# PROJECT.yaml - Portable Project Context
# Any AI agent reading this file can understand the project and continue work

name: LearningHub
path: C:\AI\Projects\LearningHub
status: active

# What is this project?
description: |
  A student-centered learning platform for teaching TIC and English.
  Students navigate knowledge through purpose-driven paths - "I want to do X"
  leads to discovering concepts as tools. Features multi-profile support
  (school lab scenario), RPG-style progress tracking, and interactive quizzes.

# Current work
current_phase: "Content & Feedback"
current_task: "Create Google Form for student feedback"
blocked_by: null

# Quick reference
tech_stack:
  - HTML/CSS/JavaScript (Static site)
  - Google Apps Script (sync tools)
  - RPG XP system (gamification)

entry_points:
  main: hub/index.html
  content: content/tic/
  docs: ROADMAP.md
  handoff: HANDOFF.md

# Navigation modes
navigation:
  by_grade: "hub/by-grade/ - I'm in Class X, what should I learn?"
  by_concept: "hub/by-concept/ - I want to understand loops"
  by_goal: "hub/by-goal/ - I want to make a game"

# Current module
current_module:
  name: "Module 3"
  dates: "Jan 8 - Feb 20, 2026"
  grades_covered: [5, 6, 7, 8]

# Milestones
milestones:
  M0_setup: complete
  M1_module3_content: complete
  M2_interactive_quizzes: complete
  M3_concept_linking: pending
  M4_progress_tracking: complete
  M5_multi_navigation: pending

# For multi-agent coordination
last_modified: "2026-01-15"
last_agent: "Claude Opus 4.5"
