name: LearningHub
type: Web Application
version: 1.0.0
status: active
created: '2026-01-12'
migrated: '2026-01-12'
description: LearningHub project
location: C:\AI\Projects\LearningHub
owner: user
tags: []
