import json
from pathlib import Path

S = Path(r"C:\00\Projects\LearningHub\_campaign\omul_la_calculator_2026_09_13\S_reparatii\cls8\lectia4-functii")
REC = "constructie/construieste.py -> H_randeaza.py xlsx -> constructie/rezultat_recalcul.txt (LibreOffice)"


def a(id_, cat, tip, inainte, dupa, ver):
    return {"id": id_, "categorie": cat, "tip": tip, "inainte_citat": inainte, "dupa_citat": dupa, "verificare": ver}


aplicate = [
    a("cls8-l4-02", "fond", "inlocuit", "Schimba nota din B4 din 10 in 3",
      "Schimba nota din B5 din 10 in 3",
      f"{REC}: foaia 'adrese' da B4=5, B5=10; foaia 'pas6_B5_3' (B5=3) da MIN 3, MAX 9, AVERAGE 6,375, COUNT 8 = exact punctul de verificare adaugat in pas."),
    a("cls8-l4-02", "fond", "adaugat", "",
      "Ar trebui sa vezi: minim 3, maxim 9, media 6,375 (sau 6.375, dupa calculator), tot 8 note.",
      f"{REC}: foaia 'pas6_B5_3' -> E2=3, E3=9, E4=6.375, E5=8."),
    a("cls8-l4-01", "fond", "inlocuit", "Scenariul: Schimbam nota 4 cu 10 in B7",
      "Scenariul: Schimbam nota 4 cu 10 in B8",
      f"{REC}: foaia 'adrese' da B8=4; foaia 'atom8_B8_10' da MIN 5, MAX 10, AVERAGE 8, COUNT 8 = tabelul atomului 8 (neschimbat, acum coerent cu adresa)."),
    a("cls8-l4-01", "fond", "inlocuit", "Schimbam B7 din 4 in", "Schimbam B8 din 4 in",
      f"{REC}: nota 4 e pe randul 8 (B8); Q_verdict_blocante: cu B8=10 -> MIN 5, AVG 8."),
    a("cls8-l4-01", "fond", "inlocuit", "Ramane 10 (aveam deja un 10 in B4)", "Ramane 10 (aveam deja un 10 in B5)",
      f"{REC}: foaia 'adrese' B5=10; MAX dupa schimbare = 10."),
    a("cls8-l4-01", "intrebare_mutata", "inlocuit", "Schimbam nota din B7 de la 4 la 10",
      "Schimbam nota din B8 de la 4 la 10",
      f"{REC}: 7,9,5,10,8,6,10,9 -> AVERAGE 8 (cheia c neschimbata); variantele trecute pe virgula zecimala (7,25 / 7,5 / 8,25)."),
    a("cls8-l4-05", "fond", "inlocuit", "Apoi sterge o nota (lasa celula goala). Compara COUNT cu COUNTA - ce e diferit?",
      "Apoi scrie cuvantul absent in locul unei note (de exemplu in B9). Compara COUNT cu COUNTA - ce e diferit?",
      f"{REC}: 'bonus_vechi_B9_gol' -> COUNT 7, COUNTA 7 (nicio diferenta, cum semnalase evaluarea); 'bonus_B9_absent' -> COUNT 7, COUNTA 8."),
    a("cls8-l4-05", "fond", "inlocuit", "Daca stergi o nota, COUNT scade cu 1.",
      "Cu \"absent\" in B9, COUNT scade la 7, iar COUNTA ramane 8.",
      f"{REC}: aceleasi doua foi; indiciul spune acum si de ce stergerea nu arata diferenta (scad amandoua la 7)."),
    a("cls8-l4-04", "excel_separator", "adaugat", "",
      "Calculatorul tau poate fi setat diferit. Pe unele calculatoare Excel desparte argumentele cu punct si virgula ( ; ), pe altele cu virgula ( , ).",
      "Textul casetei din S_CONVENTII.md §2, pus o singura data, in atomul 3, inaintea primei formule cu mai multe argumente (=MIN(B2; B5; B8)); grep pe fisier: o singura aparitie a casetei; scris fara diacritice (conventia 5)."),
    a("cls8-l4-04", "excel_separator", "inlocuit", "B2, B5, B8 ) // Minimul dintre doar 3 celule",
      "B2; B5; B8 ) // Minimul dintre doar 3 celule (sau cu virgule: =MIN(B2, B5, B8))",
      f"{REC}: foaia 'if' B4 =MIN(A1,A2,A4) -> 3 (formula valida; in xlsx separatorul e mereu virgula, v. H_randeaza.py B4)."),
    a("cls8-l4-04", "excel_separator", "inlocuit", "B2 >=5, \"Promovat\", \"Corigent\")",
      "B2 >=5; \"Promovat\"; \"Corigent\") // sau cu virgule: =IF(B2>=5, \"Promovat\", \"Corigent\")",
      f"{REC}: foaia 'if' -> 4 da Corigent, 7 da Promovat; glosar (fapte Excel): separatorul depinde de setarea regionala, pe ro-RO e ';'."),
    a("cls8-l4-04", "excel_separator", "inlocuit", "B1 scrie =IF(A1>=5,\"Promovat\",\"Corigent\")",
      "B1 scrie =IF(A1>=5;\"Promovat\";\"Corigent\") (sau cu virgule: =IF(A1>=5,\"Promovat\",\"Corigent\") ; daca Excel nu primeste formula, incearca celalalt semn)",
      f"{REC}: foaia 'if' A1=4 -> Corigent, A2=7 -> Promovat (ce promite proba)."),
    a("cls8-l4-04", "excel_separator", "inlocuit", "=IF(B2>=5, B2*2, 0).",
      "=IF(B2>=5; B2*2; 0) (sau cu virgule: =IF(B2>=5, B2*2, 0)).",
      f"{REC}: foaia 'if' A3=8, =IF(A3>=5,A3*2,0) -> 16."),
    a("cls8-l4-04", "excel_separator", "inlocuit", "=IF(B2>=5,\"Promovat\",\"Corigent\") returneaza?",
      "=IF(B2>=5; \"Promovat\"; \"Corigent\") (sau cu virgule in loc de ;) returneaza?",
      "Intrebarea atomului 9 recitita: cheia b (Promovat) ramane corecta pentru nota 7; variantele neschimbate."),
    a("cls8-l4-06", "nume_comenzi", "inlocuit", "Function Wizard - Ghidul tau pas cu pas",
      "Caseta Inserare funcție (Insert Function) - butonul fx",
      "GLOSAR_UI.md CONFIRMAT: Insert Function = Inserare funcție (surse/fx_ro.txt); VARIANTE: „Function Wizard” = nume gresit (0 aparitii in fx_en.txt). grep pe fisier dupa reparatie: 0 aparitii Wizard / Asistent."),
    a("cls8-l4-06", "nume_comenzi", "inlocuit", "Excel are un Asistent de functii (Function Wizard) care te ghideaza",
      "Excel are caseta Inserare funcție (Insert Function) care te ghideaza",
      "GLOSAR_UI.md CONFIRMAT (Insert Function); grep Wizard|Asistent = 0."),
    a("cls8-l4-06", "nume_comenzi", "inlocuit", "Acum incearca Asistentul de functii",
      "Acum incearca caseta Inserare funcție (Insert Function)",
      "GLOSAR_UI.md CONFIRMAT (Insert Function)."),
    a("cls8-l4-06", "nume_comenzi", "inlocuit", "Ai folosit Function Wizard (butonul fx) pentru a accesa functii",
      "Ai folosit caseta Inserare funcție (Insert Function), deschisa cu butonul fx, pentru a accesa functii",
      "GLOSAR_UI.md CONFIRMAT (Insert Function)."),
    a("cls8-l4-06", "nume_comenzi", "inlocuit", "Shortcut rapid: AutoComplete",
      "Shortcut rapid: Completare automată formulă (Formula AutoComplete)",
      "GLOSAR_UI.md CONFIRMAT: Formula AutoComplete = Completare automată formulă (surse/autocomplete_ro.txt)."),
    a("cls8-l4-07", "excel_separator", "inlocuit", "media e 58/8 = 7.25",
      "media e 58/8 = 7,25. Cu Excel scrii doar =AVERAGE(B2:B9) si primesti 7,25 (sau 7.25, dupa calculator) instant.",
      f"{REC}: foaia 'initial' E4 = 7.25; grep dupa zecimale cu punct: raman doar cele din parantezele „(sau ..., dupa calculator)”."),
    a("cls8-l4-07", "excel_separator", "inlocuit", "=AVERAGE(B2:B8) =20.71 (145/7).",
      "=AVERAGE(B2:B8) =20,71 (145/7; pana rotunjesti vezi 20,71429).",
      f"{REC}: foaia 'meteo' E4 = 20.7142857142857, F4 = 60.4285714285714; randarea ro-RO din evaluare (ex2_meteo.pdf) arata 20,71429."),
    a("cls8-l4-07", "excel_separator", "inlocuit", "12.5s, 11.2s, 13.8s, 10.9s, 12.1s",
      "12,5s, 11,2s, 13,8s, 10,9s, 12,1s",
      "Recitit: MIN = 10,9, MAX = 13,8 raman corecte; doar zecimala pe virgula."),
    a("cls8-l4-08", "nume_comenzi", "inlocuit", "Rotunjeste mediile la 2 zecimale (Home -> Number -> creste/scade zecimale).",
      "Afiseaza mediile cu 2 zecimale: fila Pornire (Home) > butonul Micșorare zecimală (Decrease Decimal) sau Mărire zecimală (Increase Decimal). Atentie: se schimba doar ce vezi; valoarea din celula ramane 20,714285...",
      f"GLOSAR_UI.md CONFIRMAT: Home = Pornire, Increase/Decrease Decimal = Mărire/Micșorare zecimală (surse/zecimale_ro.txt); grupul Number nu e in glosar -> nenumit. {REC}: E4 = 20.7142857 (valoarea), =ROUND(E4,2) = 20.71."),
    a("cls8-l4-09", "intrebare_mutata", "inlocuit", "Care formula calculeazamedia aritmeticaa valorilor",
      "Care formula calculeaza media aritmetica a valorilor",
      "Intrebarea AVERAGE mutata din atomul 3 in atomul 4 (care preda AVERAGE), iar intrebarea MAX (cea mai calda zi) din atomul 4 in atomul 3 (care preda MIN si MAX) - schimb intre cele doua data-quiz; recitit: in atomul 3 varianta =AVERAGE a devenit =SUM ca sa nu ceara materie din atomul urmator; M_rezultat.csv idx3/idx4 aratau best 4 / best 3."),
    a("verificare-1", "intrebare_mutata", "inlocuit", "=AVG(B1:B20)", "=MEDIAN(B1:B20)",
      "verificare.json defect 1: in atomul 4 corecta =AVERAGE(B1:B20) avea 16 vs media 12,7 (1,26). Distractorul =AVG (functie inexistenta) -> =MEDIAN (functie reala, valoarea din mijloc, nu media). Recalculat: 16 / ((14+15+12)/3 = 13,67) = 1,17 <= 1,2."),
    a("verificare-2", "fond", "adaugat", "",
      "Butonul fx sta in bara de formule, in stanga locului unde apare formula (dupa Caseta Nume (Name Box), caseta in care vezi adresa celulei, ex: E7).",
      "verificare.json defect 2: intre Caseta Nume si fx stau butoanele X (Anulare) si bifa (Introducere), deci „imediat dupa” era inexact; indiciul spune acum pozitia fata de zona formulei. Varianta corecta a intrebarii („langa Caseta Nume”) ramane valabila."),
    a("cls8-l4-09", "intrebare_mutata", "adaugat", "",
      "Unde gasesti butonul fx, care deschide caseta Inserare funcție (Insert Function)?",
      "Atomul 6 (butonul fx) primeste o intrebare despre fx, raspunsul e in textul atomului si in indiciul din Incearca; lungimi variante 37/32/30/34 (corecta sub 1,2 x media); motorul (atomic-learning.js) accepta mai multe intrebari pe atom (atom.questions.forEach)."),
    a("cls8-l4-09", "intrebare_mutata", "inlocuit", "4.8 (AVERAGE imparte la 5 celule, inclusiv cele goale)",
      "4,8 (imparte 24 la 5)",
      f"Variantele intrebarii AVERAGE-goale aduse la lungimi apropiate (19/21/16/24; inainte corecta avea 50 fata de media 32); {REC}: foaia 'quiz6' =AVERAGE(A1:A5) cu 8,6,10 -> 8, cheia a ramane corecta."),
    a("nou-salvare", "salvare", "adaugat", "",
      "Salveaza ca Clasa_Nume_Note.xlsx (de exemplu 8A_Popescu_Note.xlsx ) in folderul clasei tale - intreaba profesorul unde este.",
      "Conventia 3 aplicata la Ex. 1, care produce un fisier; recitit pe pagina: pasul e ultimul din lista exercitiului."),
    a("nou-salvare", "salvare", "adaugat", "",
      "Salveaza ca Clasa_Nume_Meteo.xlsx (de exemplu 8A_Popescu_Meteo.xlsx ) in folderul clasei tale - intreaba profesorul unde este.",
      "Conventia 3 aplicata la Ex. 2 („Creeaza un fisier Excel”); recitit pe pagina."),
    a("nou-average-ro", "fond", "inlocuit", "In Excel international se foloseste AVERAGE (nu \"MEDIA\" sau \"AVG\").",
      "In Excel se scrie AVERAGE si pe calculatoarele cu Office in romana (numele functiilor nu se traduc; nu exista \"MEDIA\" sau \"AVG\").",
      "04_mediu.md: surse/average_ro.txt „Funcția AVERAGE”, SUMA( 0 aparitii; GLOSAR_UI.md fapte Excel: numele functiilor nu se traduc."),
]

sarite = [
    {"id": "cls8-l4-03", "motiv": "Spargerea lectiei in ora 8 si ora 9 din plan e decizie de structura - ramane la profesor (conventia 5)."},
    {"id": "cls8-l4-10", "motiv": "Diacriticele vin intr-un val separat, cu poarta proprie (conventia 5); textul nou e scris in stilul fisierului."},
    {"id": "cls8-l4-11", "motiv": "Cardul din index si <title> nu se ating in valul acesta; potrivirea titlu/card depinde de spargerea lectiei (l4-03)."},
    {"id": "M-idx1-idx2", "motiv": "Alarma falsa: structura =FUNCTIE(...) e aratata chiar in atomul 1, iar MIN ca cea mai mica nota e folosit in Incearca pas 2, inainte de atomi."},
    {"id": "M-idx6", "motiv": "Intrebarea AVERAGE cu celule goale din atomul 6 se poate raspunde din atomul 4 (anterior) - nu incalca regula 6; pastrata, cu variante echilibrate, plus intrebare noua despre fx."},
    {"id": "K-ex1-ex2-ex3", "motiv": "K_rezultat.csv: toate trei „ok”; rezolvarile recalculate (Ex.2 in foaia meteo) coincid, doar zecimalele au fost trecute pe virgula."},
]

(S / "raport.json").write_text(json.dumps({"lectia": "content/tic/cls8/m1-excel-fundamente/lectia4-functii.html",
                                           "aplicate": aplicate, "sarite": sarite}, ensure_ascii=False, indent=1), encoding="utf-8")
print(len(aplicate), len(sarite))
